services: 
  postgres:
    image: postgres:15 
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: eco_user
      POSTGRES_PASSWORD: eco_password
      POSTGRES_DB: eco_db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/dats 
  redis: 
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: back-eco-go
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: eco_user
      DB_PASSWORD: eco_password
      DB_NAME: eco_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres_data:

